baseurl         = "https://suhaibsalarzai.github.io/"
theme           = "casper3"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 3
publishdir      ="docs"
#SectionPagesMenu = "main"
  title       = "Welcome to my website"

[params]
facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  description = "OS Development and Working"

  mainSections = ["post"]
  subtitle    = "OS Development and Working"
 

  author = "Muhammad Suhaib"
  authorAvatar = "uploads/prof_pic.jpg"
 
  authorWebsite = "https://github.com/suhaibsalarzai"
  authorDescription = "Web Developer, Coder"

  pageNotFoundTitle = "404 - Page not found"

  #casper 
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[menu]
[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = 90

[[menu.main]]
  name = "Projects"
  identifier = "projects"
  url = "/tags/project/"
  weight = 100

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 205
