baseurl         = "https://suhaibsalarzai.github.io/"
theme           = "casper3"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
publishdir      ="docs"
#SectionPagesMenu = "main"

[params]
  title       = "Your Bright Future is Our Mission"
  subtitle    = "OS Development and Working"

  cover       = "uploads/head1.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

 
  fbName = "sohaib.khan8434"
  githubName = "suhaibsalarzai"
  

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Muhammad Suhaib"
  authorAvatar = "uploads/prof_pic.jpg"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://github.com/suhaibsalarzai"
  authorDescription = "Web Developer, Coder"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[menu]
[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Projects"
  identifier = "projects"
  url = "/tags/project/"
  weight = 100



[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95
